name: VueDeploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.AliCloud }}
          HOST: cmp.psyhack.top
          USER: root
          APP_NAME: "CMP"
        run: |
          SSH_PATH="$HOME/.ssh"
          mkdir -p $SSH_PATH
          touch "$SSH_PATH/known_hosts"
          echo "$ACTIONS_DEPLOY_KEY" > "$SSH_PATH/id_rsa"
          chmod 700 "$SSH_PATH"
          chmod 600 "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/id_rsa"
          eval $(ssh-agent)
          ssh-add "$SSH_PATH/id_rsa"
          ssh-keyscan -t rsa $HOST >> "$SSH_PATH/known_hosts"
          ssh -o StrictHostKeyChecking=no -i $SSH_PATH/id_rsa -A -tt $USER@$HOST <<EOF
          cd /data/app/$APP_NAME
          git checkout .
          git checkout master
          git pull origin master
          nginx -s reload
          logout
          EOF
